version: '2'
services:
  node1:
    image: mariadb:10.1
    environment:
      - TERM=xterm
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_INITDB_SKIP_TZINFO=1
    volumes:
      - conf.d:/etc/mysql/conf.d
    command: mysqld --wsrep_new_cluster
  node2:
    image: mariadb:10.1
    depends_on:
      - node1
    environment:
      - TERM=xterm
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_INITDB_SKIP_TZINFO=1
    volumes:
      - conf.d:/etc/mysql/conf.d
      - entrypoint.d:/docker-entrypoint-initdb.d
    entrypoint: mysqld --wsrep_cluster_address=gcomm://node1 --user=mysql
  node3:
    image: mariadb:10.1
    depends_on:
      - node1
    environment:
      - TERM=xterm
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_INITDB_SKIP_TZINFO=1
    volumes:
      - conf.d:/etc/mysql/conf.d
      - entrypoint.d:/docker-entrypoint-initdb.d
    entrypoint: mysqld --wsrep_cluster_address=gcomm://node1 --user=mysql
  mxs:
    image: tanji/maxscale:latest
    depends_on:
      - node1
      - node2
      - node3
    volumes:
      - maxscale_galera.cnf:/etc/maxscale.cnf
    ports:
      - "4006:4006"
      - "4008:4008"
      - "6603:6603"
