version: '2'
services:
  db1:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    command: mysqld --log-bin --general-log --server-id=1 --gtid-strict-mode=1
  db2:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    command: mysqld --log-bin --general-log --server-id=2 --gtid-strict-mode=1
  db3:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    command: mysqld --log-bin --general-log --server-id=3 --gtid-strict-mode=1
  mxs:
    image: tanji/maxscale:1.4.3
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
    ports:
      - "4006:4006"
      - "6603:6603"
  mrm:
    image: tanji/replication-manager:latest
    command: replication-manager monitor --daemon --verbose --http-server --interactive=false
    volumes:
      - ./config.toml:/etc/replication-manager/config.toml
